---
- name: Run Prowler Docker Container using AWX Credentials
  hosts: localhost
  become: True
  tasks:
    - name: Execute Prowler commands for S3 using credentials from AWX
      shell: |
        AWS_ACCESS_KEY_ID={{ lookup('env', 'AWS_ACCESS_KEY_ID') }} \
        AWS_SECRET_ACCESS_KEY={{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }} \
        prowler aws --services s3
      register: prowler_output

    - name: Display the output of Prowler commands
      debug:
        msg: "{{ prowler_output.stdout }}"

    - name: Display using the echo command
      shell: echo "{{ prowler_output.stdout }}"

    - name: Display Prowler version
      shell: prowler --version
      register: prowler_version_output

    - name: Display Prowler version output
      debug:
        var: prowler_version_output.stdout
