---
- name: Run Prowler Docker Container using AWX Credentials
  hosts: localhost
  become: True

  vars_prompt:
    - name: choice
      prompt: "Choose an option (1 to run with Access Key/Secret, anything else to skip)"
      private: no

  tasks:
    - name: Debug user choice
      debug:
        msg: "User choice is: '{{ choice }}'"

    - name: Validate user choice
      fail:
        msg: "Invalid choice. Please choose '1' to run or any other key to skip."
      when: choice not in ['1']

    - name: Execute Prowler commands for elb using credentials from AWX and generate CSV output
      shell: |
        AWS_ACCESS_KEY_ID={{ lookup('env', 'AWS_ACCESS_KEY_ID') }} \
        AWS_SECRET_ACCESS_KEY={{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }} \
        prowler aws --services elb -M csv
      register: prowler_output
      ignore_errors: yes

    - name: Find the CSV file
      find:
        paths: "/runner/project/output/"
        patterns: "prowler-output-*.csv"
      register: csv_file

    - name: Read the CSV file
      command: cat "{{ csv_file.files[0].path }}"
      register: csv_output

    - name: Display the CSV output of Prowler commands
      debug:
        msg: "{{ csv_output.stdout }}"

    - name: Display using the echo command
      shell: echo "{{ prowler_output.stdout }}"

    - name: Display Prowler version
      shell: prowler --version
      register: prowler_version_output

    - name: Display Prowler version output
      debug:
        var: prowler_version_output.stdout
