---
- name: Run Prowler Docker Container using AWX Credentials
  hosts: localhost
  become: True
  tasks:
    - name: Execute Prowler commands for elb using credentials from AWX and generate CSV output
      shell: |
        AWS_ACCESS_KEY_ID={{ lookup('env', 'AWS_ACCESS_KEY_ID') }} \
        AWS_SECRET_ACCESS_KEY={{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }} \
        prowler aws --services eventbridge -M csv
      register: prowler_output
      ignore_errors: yes
    - name: finding the generatde outputs
      shell: cat /runner/project/output/*
      register: csv_output
      #ignore_errors: yes
    - name: Display Prowler files output
      debug:
        var: csv_output.stdout
