---
- name: Run Prowler Docker Container using either Access Key or ARN with Web Identity Token
  hosts: localhost
  become: True

  vars:
    choice: "{{ choice }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    role_arn: "{{ role_arn }}"
    region: "{{ region }}"
    services: "{{ services }}"
    web_identity_token: "{{ web_identity_token }}"

  tasks:
    - name: Validate user choice
      fail:
        msg: "Invalid choice. Please choose 1 for Access Key/Secret or 2 for ARN with Web Identity Token."
      when: choice not in ['1', '2']

    - name: Check if Access Key and Secret Key are required but not provided
      fail:
        msg: "Access Key and Secret Key are required for option 1"
      when: choice == '1' and (aws_access_key == "" or aws_secret_key == "")

    - name: Check if role ARN is required but not provided
      fail:
        msg: "Role ARN is required for option 2"
      when: choice == '2' and role_arn == ""

    - name: Check if web identity token is required but not provided
      fail:
        msg: "Web identity token is required for option 2"
      when: choice == '2' and web_identity_token == ""

    # Option 1: Using Access Key and Secret Key
    - name: Execute Prowler commands using Access Key and Secret Key
      shell: |
        AWS_ACCESS_KEY_ID={{ aws_access_key }} \
        AWS_SECRET_ACCESS_KEY={{ aws_secret_key }} \
        prowler aws --services {{ services }} -M csv
      register: prowler_output_access
      ignore_errors: yes
      when: choice == '1'

    # Option 2: Using ARN with Web Identity Token
    - name: Assume Role with AWS STS using Web Identity Token
      shell: |
        aws sts assume-role-with-web-identity --role-arn {{ role_arn }} --role-session-name prowlerSession --region {{ region }} --output json --web-identity-token {{ web_identity_token }}
      register: sts_output_web_identity
      ignore_errors: yes
      when: choice == '2'

    - name: Parse STS output for Web Identity Token
      set_fact:
        aws_access_key_id_web: "{{ sts_output_web_identity.stdout | from_json | json_query('Credentials.AccessKeyId') }}"
        aws_secret_access_key_web: "{{ sts_output_web_identity.stdout | from_json | json_query('Credentials.SecretAccessKey') }}"
        aws_session_token_web: "{{ sts_output_web_identity.stdout | from_json | json_query('Credentials.SessionToken') }}"
      when: choice == '2'

    - name: Execute Prowler commands using assumed role credentials for Web Identity Token
      shell: |
        AWS_ACCESS_KEY_ID={{ aws_access_key_id_web }} \
        AWS_SECRET_ACCESS_KEY={{ aws_secret_access_key_web }} \
        AWS_SESSION_TOKEN={{ aws_session_token_web }} \
        prowler aws --services {{ services }} -M csv
      register: prowler_output_web_identity
      ignore_errors: yes
      when: choice == '2'

    # Common Task: Display Prowler output
    - name: Display Prowler output
      debug:
        var: prowler_output_access.stdout if choice == '1' else prowler_output_web_identity.stdout
