---
- name: Assume Role and Run Prowler
  hosts: localhost
  become: true
  vars:
    role_arn: "arn:aws:iam::663552238330:role/prowler"  # Replace with your role ARN
    role_session_name: "prowlerSession"
    services: "elb"  # Specify the AWS services to scan with Prowler

  tasks:
    - name: Assume the AWS Role
      shell: |
        aws sts assume-role --role-arn {{ role_arn }} --role-session-name {{ role_session_name }} --output json
      register: assume_role_output
      changed_when: false

    - name: Set AWS Credentials from Assume Role
      set_fact:
        aws_access_key_id: "{{ assume_role_output.stdout | from_json | json_query('Credentials.AccessKeyId') }}"
        aws_secret_access_key: "{{ assume_role_output.stdout | from_json | json_query('Credentials.SecretAccessKey') }}"
        aws_session_token: "{{ assume_role_output.stdout | from_json | json_query('Credentials.SessionToken') }}"
    
    - name: Export AWS environment variables
      shell: |
        export AWS_ACCESS_KEY_ID={{ aws_access_key_id }}
        export AWS_SECRET_ACCESS_KEY={{ aws_secret_access_key }}
        export AWS_SESSION_TOKEN={{ aws_session_token }}
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
        AWS_SESSION_TOKEN: "{{ aws_session_token }}"

    - name: Run Prowler for specified AWS services
      shell: |
        prowler aws --services {{ services }}
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
        AWS_SESSION_TOKEN: "{{ aws_session_token }}"
      register: prowler_output

    - name: Display Prowler output
      debug:
        msg: "{{ prowler_output.stdout }}"
