---
- name: Run Prowler Docker Container
  hosts: localhost
  become: true
  vars:
    aws_access_key_id: "YOUR_AWS_ACCESS_KEY_ID"
    aws_secret_access_key: "YOUR_AWS_SECRET_ACCESS_KEY"
    aws_region: "YOUR_AWS_REGION"

  tasks:  
    - name: Execute multiple Prowler commands in one line
      shell: |
        AWS_ACCESS_KEY_ID={{ aws_access_key_id }} \
        AWS_SECRET_ACCESS_KEY={{ aws_secret_access_key }} \
        AWS_REGION={{ aws_region }} \
        prowler aws --services ec2
      register: prowler_output
      ignore_errors: yes

    - name: Display formatted Prowler results
      debug:
        msg: "{{ formatted_results }}"

    - name: Check Prowler version
      shell: prowler --version
      register: prowler_version_output

    - name: Displaying the version output
      debug:
        msg: "{{ prowler_version_output.stdout }}"
