---
- name: Run Prowler Docker Container using AWX Credentials
  hosts: localhost
  become: True
  tasks:
    - name: Execute Prowler commands for S3 using credentials from AWX and generate CSV output
      shell: |
        AWS_ACCESS_KEY_ID={{ lookup('env', 'AWS_ACCESS_KEY_ID') }} \
        AWS_SECRET_ACCESS_KEY={{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }} \
        prowler aws --services s3 -M csv
      register: prowler_output
      ignore_errors: yes

    - name: Wait for the CSV file to be generated
      wait_for:
        path: "/runner/project/output/prowler-output-*.csv"
        state: present
        timeout: 300

    - name: Find the CSV file
      find:
        paths: "/runner/project/output/"
        patterns: "prowler-output-*.csv"
      register: csv_file

    - name: Read the CSV file
      command: cat "{{ csv_file.files[0].path }}"
      register: csv_output

    - name: Display the CSV output of Prowler commands
      debug:
        msg: "{{ csv_output.stdout }}"

    - name: Display using the echo command
      shell: echo "{{ prowler_output.stdout }}"

    - name: Display Prowler version
      shell: prowler --version
      register: prowler_version_output

    - name: Display Prowler version output
      debug:
        var: prowler_version_output.stdout
