---
- name: Run Prowler Docker Container using ARN for Role Assumption in AWX
  hosts: localhost
  become: True
  vars:
    role_arn: "{{ role_arn }}"  # This will be passed from AWX as an extra variable
    region: "{{ region }}"  # This will be passed from AWX as an extra variable
    services: "{{ services }}"  # List of services passed from AWX as an extra variable (e.g., 's3,vpc,elb')

  tasks:
    - name: Assume Role with AWS STS
      shell: |
        aws sts assume-role --role-arn {{ role_arn }} --role-session-name prowlerSession --region {{ region }} --output json
      register: sts_output
      ignore_errors: yes

    - name: Parse STS output
      set_fact:
        aws_access_key_id: "{{ sts_output.stdout | from_json | json_query('Credentials.AccessKeyId') }}"
        aws_secret_access_key: "{{ sts_output.stdout | from_json | json_query('Credentials.SecretAccessKey') }}"
        aws_session_token: "{{ sts_output.stdout | from_json | json_query('Credentials.SessionToken') }}"

    - name: Execute Prowler commands using assumed role credentials for specified services
      shell: |
        AWS_ACCESS_KEY_ID={{ aws_access_key_id }} \
        AWS_SECRET_ACCESS_KEY={{ aws_secret_access_key }} \
        AWS_SESSION_TOKEN={{ aws_session_token }} \
        prowler aws --services {{ services }} -M csv
      register: prowler_output
      ignore_errors: yes

    - name: Find the generated outputs
      shell: cat /runner/project/output/*
      register: csv_output
      ignore_errors: yes

    - name: Display Prowler files output
      debug:
        var: csv_output.stdout
